
stages:
  # Code 1
  - code: 358
  # Code 2
  - code: 732
  # Code 3
  - code: 971
  # Code 4
  - code: 521
  # Code 5
  - code: 285
  # Code 6
  - code: 622
  # Code 7
  - code: 710
  # Code 8
  - code: 471
  # Code 9
  - code: 123
  # Code 10
  - code: 829
  # Code 11
  - code: 146
  # Code 12
  - code: 538